In [50]:
import numpy as np

# Creation of Array :
- Step 1 : import numpy as np 
- Step 2 : var_name = np.array( [ list pass ] )

- > To check dimension of array : var_name.ndim
- > To check size (i.e. no. of elements in array ) : var_name.size 

- Shortcut to create a n-d array

```python
import numpy as np

arrn = np.array([1,2,3,4], ndmin=10)

```

In [51]:
squares = [2,4,8,16,32,64]

squ_arr = np.array(squares)

print(squ_arr, type(squ_arr))

# check dimension
print(squ_arr.ndim)


# check size 
print(squ_arr.size)

[ 2  4  8 16 32 64] <class 'numpy.ndarray'>
1
6


In [52]:
# Create a n-d array 

squ_5arr = np.array(squares,ndmin=5)

print(squ_5arr,squ_5arr.ndim, squ_5arr.shape)

[[[[[ 2  4  8 16 32 64]]]]] 5 (1, 1, 1, 1, 6)


 # NumPy array with functions (special arrays): 

In [53]:
# 1. Create an array with a specific range 

range_array = np.arange(1,25,2)  # start stop step 
print(range_array)


# Build a 1-d array
# > will use reshape to make it to n-d further .

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [54]:
# 2. Create array with values that are spaced linearly at a specific interval

spaced_array = np.linspace(0,1,5) # start stop no._of_elements

print(spaced_array)

[0.   0.25 0.5  0.75 1.  ]


In [55]:
# 3. logarithmic scale array 

log_array = np.logspace(1,3,5)  # 10^1 to 10^3 5 values 

print(log_array)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [56]:
#  4. array filled with zeroes or ones : 

zero_array = np.zeros([4])
print(zero_array)


# you can also define the dimension and number of elements like 
print()
# create array filled with zeros having 4 rows and 5 columns 


print(np.zeros([4,5], dtype=int))  # we can also define data type 

[0. 0. 0. 0.]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [57]:
print(np.ones(6))  # 1-d array

print()

print(np.ones([3,2,4]))

[1. 1. 1. 1. 1. 1.]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [58]:
#  5 . Create array with our choice of value 

custom_arr = np.full([4,5],7)  # dimension [rows,col], value
print(custom_arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [59]:
# 6. Empty array : replace `.empty` with zeroes and pass dimension as same 

# It is uninitialised array
empty_arr =  np.empty(6,dtype=int)
print(empty_arr)


# > `Note `: In empty array it occupies the memory of previous build array in the memory if left unfiled .

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408]


In [60]:
# 7. identity matrix : 
# np.eye(dimension)
# It create a dimension x dimension identity matrix 


print(np.eye(4,4,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Array creation with Random numbers

In [ ]:
print(np.random.rand(10))

[0.80792661 0.34351722 0.4752379  0.60247082 0.48592857 0.698096
 0.85971757 0.62340075 0.69151989 0.70402546]


- Numpy provide you `random` module to work with random numbers.


In [67]:
print(np.random.rand(2,3))  # Don't provide square bracket as dimension it will be treated as list in random module 

[[0.21143577 0.88215753 0.04951566]
 [0.23518065 0.94559649 0.96858443]]


In [ ]:
# 1. rand() : Returns a random float between 0 and 1.
# It generates the 1-d array of random value between 0 & 1 of number of elements provided .
# To generate a random array of n dimension just pass rows and coloumns in place of number of elements

var_name = np.random.rand(4,2)
print(var_name)


[[0.15776021 0.93351427]
 [0.30065916 0.0201358 ]
 [0.76289957 0.58924893]
 [0.79945261 0.76186626]]


In [69]:
# Q : Generate an array containing numbers from 0 to 1 and having 3-dimension with 3,4,2 elements 

print(np.random.rand(3,4,2))

[[[0.60280338 0.89117536]
  [0.98738288 0.23270472]
  [0.08083654 0.51731651]
  [0.81872426 0.7712603 ]]

 [[0.32807248 0.5180383 ]
  [0.25974975 0.79627645]
  [0.73422734 0.2752349 ]
  [0.35520318 0.20208785]]

 [[0.98126956 0.61831922]
  [0.08639617 0.38866209]
  [0.86325904 0.95603056]
  [0.87919991 0.82327829]]]


In [72]:
# Similiarly To generate a int in range randint(). 

print(np.random.randint(1,100, size=25))

#  generate a random integer array containing 3 rows and 5 elements in each row in b/w 1 to 10
print()
print(np.random.randint(1,11, size=(3,5)))

[83 66 49 40 30 46 41 31 88 77 83 27 53 65 95 36 59 32 60 84  6 35 26 84
 86]

[[ 1 10  6  1  4]
 [ 1  9  7  8  6]
 [ 4  9  4  2  1]]


In [73]:
# 2. randn() :  the function is used to generate random value close to zero . This may return possitive or negative value as well.
# random floats from standard normal distribution 

print(np.random.randn(2,4))

[[-0.63877452  1.1766362  -0.26928962  0.40165913]
 [ 0.41651298 -0.42450791  0.00854628  0.23657627]]
