In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b=np.array([5])  # behave as [5,5,5,5]

print(a+b)

[6 7 8 9]


In [ ]:
c = np.array([[1],[2],[3]]) # 3x1
d = np.array([1,2,3])  # 1x3
print(c+d)  # 3x3

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
e = np.array([[2,3,4],[2,3,4]])   # 2x3
f = np.array([[2,3],[4,5],[1,7]])   # 3x2

#  operations not possible dimensions different and not anyone of them=1 dim

print(e+f)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 