In [2]:
import numpy as np 

In [3]:
a = np.array([[2,3,4],[3,4,5]])  #2-d shape 2,3
b = np.array([4,5,4]) # 1-d shpae 3
c = np.array([[3,2],[4,5],[1,2]]) # 2-d shape 3,2
d = np.array([[2,3,4],[5,4,3]]) # 2-d shape : 2,3


- In performing mathematics operations shape should remain same in multi dim array

In [4]:
print(a.ndim,a.shape,"\n")
print(b.ndim,b.shape,"\n")
print(c.ndim,c.shape,"\n")
print(d.ndim,d.shape,"\n")

2 (2, 3) 

1 (3,) 

2 (3, 2) 

2 (2, 3) 



In [5]:
# addition 

print(b+d)

[[6 8 8]
 [9 9 7]]


In [6]:
# addition 
print(a+d,"\n")

# subtraction
print(a-d,"\n")

# division : float
print(a/d,"\n")

# division : int
print(a//d,"\n")

# multiply
print(a*d,"\n")

# modulo 
print(a%b,"\n")

# exponential
print(a**2)



[[4 6 8]
 [8 8 8]] 

[[ 0  0  0]
 [-2  0  2]] 

[[1.         1.         1.        ]
 [0.6        1.         1.66666667]] 

[[1 1 1]
 [0 1 1]] 

[[ 4  9 16]
 [15 16 15]] 

[[2 3 0]
 [3 4 1]] 

[[ 4  9 16]
 [ 9 16 25]]


### Some universal functions :

In [11]:
# a = np.array([[2,3,4],[3,4,5]])  
# b = np.array([4,5,4]) 
# c = np.array([[3,2],[4,5],[1,2]]) 
# d = np.array([[2,3,4],[5,4,3]]) 

e = np.array([3,2,4])
# sqrt
print(np.sqrt(a**4),"\n")

# exponential e^x
print(np.exp(b))


# transpose a matrix : 
print(d.transpose())


# concatenation 
print(np.concatenate([b,e]))
# while using concatenate always use [] or () while passing arguments

print()

print(np.concatenate([a,d]))


# split 
np.split(c,3)


[[ 4.  9. 16.]
 [ 9. 16. 25.]] 

[ 54.59815003 148.4131591   54.59815003]
[[2 5]
 [3 4]
 [4 3]]
[4 5 4 3 2 4]

[[2 3 4]
 [3 4 5]
 [2 3 4]
 [5 4 3]]


[array([[3, 2]]), array([[4, 5]]), array([[1, 2]])]

In [ ]:

# vstack & hstack

print(np.vstack((a,d)))

print()

print(np.hstack((a,d)))


#  we can also do as 
# np.stack((a,d), axis=)

#  axis = 0 : vstack
# axis = 1 : hstack

[[2 3 4]
 [3 4 5]
 [2 3 4]
 [5 4 3]]

[[2 3 4 2 3 4]
 [3 4 5 5 4 3]]


# Indexing & Slicing : 
### Indexing : 
- Access element through index 1-d : var[ index ] . 
- Access element through index 2-d : var[ row, col ] . 
- Access element through index 3-d : var[ row, row, col ] .
- Array[-1] : last element
- -n -(n-1) ...... -3 -2 -1
### Slicing of array :
var_name[start_index : end_index : step]
- Non-inclusive end 
- if want a slicing till end than don't need to give end index
- By default step is 1
- In 2-d array first pass row number than slicing same .

In [ ]:
slice_arr = np.array([2,3,4,5,6,7,8,12,3,4])

print(slice_arr[-2:-8:-1])   # start : stop : step

# slicing with negative index we have to put step value

[ 3 12  8  7  6  5]


In [ ]:
#  In 2-d slicing 
# slice[ row_slice ,col_slice]

matrix = np.random.randint(4,100, size=(3,3))
print(matrix)
print()

# slice : 1st row,2nd row and 2nd and 3rd column
# Remember 0-based indexing

print(matrix[0:3, 1:4])

[[94 93 69]
 [35 78 43]
 [72 66 16]]

[[93 69]
 [78 43]
 [66 16]]


# Iterating NumPy Array :
- simple loops and nested loops
- Function to iterate : `np.nditer(var)`
- to get indexing along with value we use `ndneumerate()` function . 


In [ ]:
var = np.array([[1,2,3,4,5],[2,6,7,4,3]])
for i in np.nditer(var):
    print(i)

1
2
3
4
5
2
6
7
4
3


In [ ]:
# To get indexing with value 
for i,j in np.ndenumerate(var):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 2
(1, 1) 6
(1, 2) 7
(1, 3) 4
(1, 4) 3



## [Copy v/s View :](./Copy_View.py)

| Copy                                                         | View                                                                                                        |
|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| Copy Owns the data                                           | View does not own the data                                                                                  |
| Copy of array is a new array                                 | Ony view of original array                                                                                  |
| The changes made in copy data does not reflect in main array | any changes made to view array reflect in original array & changes made in original array reflects in view  |

- By default is view if we have to build copy than apply `.copy()` function at last